name: Basic Checkout Lab

on:
  push:
    branches:
      - main

jobs:
  basic-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Show system info
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Operating System: $(uname -a)"
          echo "Current Directory: $(pwd)"

      - name: Check versions
        run: |
          echo "Node version: $(node --version || echo 'Node not installed')"
          echo "Python version: $(python --version || echo 'Python not installed')"
          echo "Git version: $(git --version)"

      - name: Show current date and time
        run: date

      - name: Show available disk space
        run: df -h

      - name: Show memory usage
        run: free -h

      env:
        CUSTOM_MESSAGE: "Hello from GitHub Actions!"
      
      - name: Show custom message
        run: echo "$CUSTOM_MESSAGE"

      - name: Conditional step
        if: github.event_name == 'push'
        run: echo "This was triggered by a push event"
